services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=video_manage_system
    volumes:
      - vms_mysql_data:/var/lib/mysql
    ports:
      - "6932:3306"
    networks:
      - app-network

  backend-va:
    build: .
    container_name: vms-backend-va
    environment:
      - VMS_VA_DATABASE_HOST=mysql-db
    ports:
      - "6590:6590"
    command: ./entrypoint.sh
    depends_on:
      - mysql-db
    networks:
      - app-network

volumes:
  vms_mysql_data:

networks:
  app-network:
    driver: bridge